pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh '''
                . venv/bin/activate
                python -m pytest tests/
                '''
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                    sonar-scanner \
                      -Dsonar.projectKey=SonarQube-App \
                      -Dsonar.sources=. \
                      -Dsonar.host.url=http://34.227.21.112:9000
                    '''
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                scp -r * ubuntu@52.54.220.19:/home/ubuntu/webfiles/
                ssh ubuntu@52.54.220.19 'cd /home/ubuntu/webfiles && python3 app.py &'
                '''
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
